######################################################################
# Automatically generated by qmake (1.07a) Mon Sep 13 18:37:46 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += . ./english

TARGET = neuner

# Input
HEADERS += chips.h   config.h gamelib.h   window.h   english/lang.h
SOURCES += chips.cpp main.cpp gamelib.cpp window.cpp
