######################################################################
# Automatically generated by qmake (1.07a) Sun Apr 10 17:38:13 2005
######################################################################

TEMPLATE = app
INCLUDEPATH += . english
TARGET = master

# Input
HEADERS += config.h game.h gamelib.h window.h english/lang.h
SOURCES += game.cpp gamelib.cpp main.cpp window.cpp
