######################################################################
# Automatically generated by qmake (1.07a) Mon Sep 13 18:05:10 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += . ./english

# Input
HEADERS += chips.h english/config.h gamelib.h window.h
SOURCES += chips.cpp gamelib.cpp main.cpp window.cpp
